# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node


      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
          
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            
      - run: sudo apt-get install default-jdk
      
      # Install Chrome.
      - run: sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
      - run: sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install google-chrome-stable
      
      # Install dependences
      - run: npm install
      
#       - run:
#           name: Install Selenium
#           command: |
#             ./node_modules/.bin/selenium-standalone install         
#       - run:
#           name: Start Selenium
#           command: |
#             ./node_modules/.bin/selenium-standalone start         
#           background: true

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npx wdio
