# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: timbru31/java-node

    working_directory: ~/repo

    steps:
      - checkout
          
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
            
      # Install Chrome.
      - run:
          name: Install Chrome
          command: |
            curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
            apt-get -y update
            apt-get -y install google-chrome-stable
      
      # Install dependences
      - run: npm install
      
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npx wdio
